#!/bin/bash
#
THEMES=("Large" "Normal" "Quit")
DIR="$HOME/.config/herbstluftwm"


PS3='Which theme would you like?'

select gaps in "${THEMES[@]}"; do
    case "$gaps" in
        "Large")
            cd "$DIR" || 'exit'; rm autostart; wget https://gitlab.com/jped/dotfiles/-/raw/master/.config/herbstluftwm/backup/autostart1; mv autostart1 "$HOME/.config/herbstluftwm/autostart"; chmod +x autostart; herbstclient reload
            exit
            ;;
        "Normal")
            cd "$DIR" || 'exit'; rm autostart; wget https://gitlab.com/jped/dotfiles/-/raw/master/.config/herbstluftwm/autostart; chmod +x autostart; herbstclient reload
            exit
            ;;
        "Quit")
            exit
            ;;
    esac
done




