#!/bin/bash

set -eo pipefail

repo=$1
file=$2

if [ -z "$1" ] || [ -z "$2" ]; then
    echo ERROR: Please include repo name followed by filename or \* \(glob\) for entire dir.
  exit 1
fi

git status;
 
read -p "Would you like to push changes?: " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]; then
    if [[ "$2" = * ]]; then
        git add .
    else
        git add "$file"
    fi

printf "add message\n"
read -r message

    git commit -m "$message"
    git push git@gitlab.com:jped/"$repo".git;
    git push git@github.com:jdpedersen1/"$repo".git
elif [[ $REPLY =~ ^[Nn]$ ]]; then 
    printf "\nNo changes pushed"
    sleep 2
    exit
fi

