#!/bin/bash

set -eo pipefail

repo=$1
file=$2
commit_message="$2 added"

git add "$file"
git commit -m "$commit_message"
git push git@gitlab.com:jped/"$repo".git;
git push git@github.com:jdpedersen1/"$repo".git


