#!/usr/bin/env bash

# Created By: Jake@Linux
# Created On: Sun 14 May 2023 03:24:07 PM CDT
# Project: 


choice="$(fzf --prompt="Which Program Would You Like To Run : " --border=rounded --margin=5% --color='fg:104,fg+:255,pointer:12,hl:255,hl+:12,header:12,prompt:255' --height 100% --reverse --header="                    PROGRAMS " --info=hidden --header-first)" 
exec devour "$choice"

