#!/usr/bin/env bash

SCRATCHPAD_NAME=$1

case "$1" in

    qutebrowser)
        entry="qutebrowser"
        ;;
    Alacritty)
        entry="alacritty -e wingeo"
        ;;
    Calc)
        entry="qalculate-gtk"
        ;;
    Mail)
        entry="mailspring"
        ;;
    Menu)
        entry="kitty --class launch -e launch.sh"
esac

xdotool search --onlyvisible --class "$1" windowunmap \
    || xdotool search --classname "$1" windowmap \
    || $entry &

