#!/usr/bin/env bash

case "$1" in

	scratchpad) 		
        entry="alacritty --class scpad -t scratchpad" 		
        ;;
	Menu) 		
        entry="alacritty --class launch -t menu -e launch.sh"		
        ;;
    vsrc)
        entry="alacritty --class src -t vsrc -e vsp2"
        ;;
    Music)
        entry="alacritty -t Music -e ncmpcpp"
        ;;
    Todo)
        entry="alacritty -t Todo -e schedule.sh"
        ;;
esac

xdotool search --onlyvisible --name "$1" windowunmap \
    || xdotool search --name "$1" windowmap \
    || $entry &

