#!/bin/bash

ARGS=$(getopt --options cvh --long "check,version,help" -- "$@")

eval set --"$ARGS"

check="false"
version="false"
help="false"

while true; do 
    case "$1" in
        -c|--check)
            check="true"
            shift;;
        -v|--version)
            version="true"
            shift;;
        -h|--help)
            help="true"
            shift;;
    esac
done

if [ "$check" == true ]; then
    search=$(xbps-query -s "$2" | wc -l)
    if [ "$search" -ge "1" ]; then
        ver=$(grep version ~/.local/pkgs/void-packages/srcpkgs/"$2"/template)
        echo "$ver"
    else
        echo "done"
    fi
fi

