#!/bin/bash

ARGS=$(getopt --options cvh --long "check,version,help" -- "$@")

eval set --"$ARGS"

check="false"
version="false"
help="false"



while true; do 
    case "$1" in
        -c|--check)
            check="true"
            shift;;
        -v|--version)
            version="true"
            shift;;
        -h|--help)
            help="true"
            shift;;
        --)
            shift
            break;;
    esac
done

search="$(ls "$HOME"/.local/pkgs/void-packages/srcpkgs | grep "$1")"


if [ "$check" == true ]; then
    avail="$(ls "$HOME"/.local/pkgs/void-packages/srcpkgs | grep "$1" | wc -l)"
    if [ "$avail" -gt 0 ]; then
        echo "$search"
    fi
fi


if [ "$version" == true ]; then
    ver=$(grep version= ~/.local/pkgs/void-packages/srcpkgs/"$1"/template)
    echo "$ver"
fi

